version: "3.8"

services:
  api:
    image: "node:17"
    container_name: "api"
    working_dir: /api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    command: 
      - /bin/sh
      - -c
      - |
        yarn set version berry
        yarn set version latest
        yarn
        yarn build
        yarn start:prod

